version: "3"
services:
  jupyter:
    image: jupyter/base-notebook
    container_name: mgt-4067
    ports:
    - "8888:8888"
    volumes:
    - ./notebooks:/home/jovyan/work
    environment:
    - JUPYTER_TOKEN=easy123
